version: '3.8'

services:
  # --- 1. API GATEWAY (ОСНОВНОЙ БЭКЕНД) ---
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend 
    ports:
      - "8080:8000"             
    networks:
      - pdm-network
    environment:
      ML_SERVICE_URL: "http://ml-service:8000"   
      DATA_SERVICE_URL: "http://data-service:8000" 
      PYTHONPATH: "/app"         
    volumes:                    
      - ./backend:/app/backend 
      - ./configs:/app/configs   
      - ./src:/app/src           
      - ./models:/app/models     
      - ./backend/requirements.txt:/app/requirements.txt 
    restart: unless-stopped      

  # --- 2. ML INFERENCE SERVICE ---
  ml-service:
    build:
      context: .
      dockerfile: ml-service/Dockerfile.ml
    networks:
      - pdm-network
    environment:
      MODELS_DIR: "/app/models"
      PYTHONPATH: "/app"       
    volumes:                    
      - ./models:/app/models    
      - ./configs:/app/configs  
      - ./src:/app/src         
      - ./data:/app/data         # Data-service загружает data/, но ml-service тоже нужен, чтобы получить сырые данные для PredictRequest, который будет в go-backend. 
                                 # Либо: backend/app.main сам загрузит, и не надо будет для ml-service
    restart: unless-stopped

  # --- 3. DATA SERVICE ---
  data-service:
    build:
      context: .
      dockerfile: data-service/Dockerfile.data
    networks:
      - pdm-network
    environment:
      PYTHONPATH: "/app"        
    volumes:                   
      - ./data:/app/data        
      - ./configs:/app/configs 
      - ./src:/app/src           
    restart: unless-stopped
    
  # --- 4. FRONTEND SERVICE (НОВЫЙ!) ---
  frontend:
    build:
      context: .                 # Контекст сборки - корневая папка проекта
      dockerfile: frontend/Dockerfile.frontend # Путь к Dockerfile React/Vite фронтенда
    ports:
      - "3000:3000"              # Frontend будет доступен на http://localhost:3000
    networks:
      - pdm-network
    depends_on:                  # Frontend зависит от API Gateway
      - backend
    environment:
      # Фронтенд будет обращаться к внешнему порту 8080 основного бэкенда.
      # Важно: для React/Vite проекта, вам не нужен `NEXT_PUBLIC_API_URL`, а нужен
      # прямое URL API для fetch/axios. Vite подставляет это в процесс.env
      VITE_API_URL: "http://localhost:8080/api" # (Vite_переменные окружения начинаются с VITE_)
      # Использовать ли моки на фронтенде
      VITE_USE_MOCKS: "true" # "true" or "false" (Если "false", бэкенд должен быть запущен)
    restart: unless-stopped


# --- ОПРЕДЕЛЕНИЕ СЕТИ ---
networks:
  pdm-network:
    driver: bridge